### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by MontAmore** [Clickopolis/clickopolis#34]
clicked on the link, norton popped up telling me it was spyware, blocked the page, and gave me a long report on how your website redirected to a link recognized in the database as a fake popup scam that was targeting my hardware. why????

**Comment by emzinnia** [comment]
Hi,

Sorry I haven't maintained this project in years. Hence I no longer own the domain, so I suspect someone bought it with the intent of spreading malware with it. Sorry for the inconvenience -- I've removed it from the repo
